
services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports: 
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./alert.rules.yml:/etc/prometheus/alert.rules.yml
    depends_on:
      - flask-app
    networks:
      - monitoring

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    networks:
      - monitoring

  flask-app:
    build: .
    container_name: flask-app
    ports:
      - "5000:5000"  # Flask app
      - "8000:8000"  # Metrics
    environment:
      - FLASK_DEBUG=1
    volumes:
      - .:/app  # For development (hot-reload)
    networks:
      - monitoring
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 5s
      retries: 3
  
  node-exporter:
    image: prom/node-exporter
    ports:
      - "9100:9100"
    networks:
      - monitoring 

networks:
  monitoring:
    driver: bridge